name: ds_new  # Change this to your environment name
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scikit-learn
  - xgboost
  - torch
  - torchvision
  - torchaudio
  - matplotlib
  - seaborn
  - tqdm
  - joblib
  - jupyterlab
  - ipython
  - imbalanced-learn
  - optuna
  - shap
  - pip
  - pip:
      - google-colab
      - datasets  # If using Hugging Face datasets
